name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test

      - name: Build the app
        run: npm run build

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: simple_deployment_pipeline
    concurrency: deploy-group
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    name: Bump version and tag release
    runs-on: ubuntu-20.04
    needs: [simple_deployment_pipeline, deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline, deploy]
    steps:
      - name: Notify Discord on Success
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v2
        with:
          title: A new version of Pokedex deployed
          message: to https://full-stack-open-pokedex-thrumming-hill-3413.fly.dev/ by ${{ github.actor }}
          include_image: false
          username: GitHub
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Failure
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v2
        with:
          title: Build failed
          message: commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
          include_image: false
          username: GitHub
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
